In [1]:
import pandas as pd 
import matplotlib as plt 
import numpy as np 
import os

In [2]:
df = pd.read_csv("lifestyle_dataset.csv")
df.head()

,Age,Gender,Occupation,Height_cm,Weight_kg,Country,Archetype,DailyCalorieIntake,SleepHours,PhysicalActivity_min,...,ScreenTime_hrs,CommuteTime_hrs,TasksCompleted_day,ProductivityScore,StressLevel,MoodScore,MeditationTime_min,CodingHours_day,CodingProblems_day,DebuggingRatio
0,56,M,Manager,180.4,96.0,UK,Health Enthusiast,2602,8.2,64,...,4.1,0.0,5,6.1,4.8,9.1,21,1.3,1,0.33
1,46,M,Student,180.7,78.7,France,Student,2226,6.9,52,...,5.3,0.0,0,1.6,4.9,4.1,18,3.4,1,0.57
2,32,F,Unemployed,169.9,55.8,India,Student,1943,5.0,18,...,6.4,1.8,5,3.3,6.2,5.7,1,2.9,1,0.28
3,60,F,Teacher,172.1,64.6,Canada,Workaholic,1933,5.7,30,...,10.9,0.9,10,4.3,9.2,3.5,2,5.3,7,0.31
4,25,F,Student,156.5,53.5,Australia,Sedentary,1876,6.3,2,...,3.0,1.7,5,1.4,8.1,5.5,0,0.0,0,0.47

In [3]:
len(df)

10000